// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhljgkcresjmjleeqqtn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhobGpna2NyZXNqbWpsZWVxcXRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NTE2MDQsImV4cCI6MjA2MjQyNzYwNH0.1m3CroAlzKM3tDTPLiw267Cs-N_y0vuud26HqLWptFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);